<a href="https://colab.research.google.com/github/Deepeck05/Artificial_Inteligence_Project/blob/main/AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello Deepeck")

Hello Deepeck


In [ ]:
a=[1,2,3,4]
print(a)

[1, 2, 3, 4]


In [ ]:
a=[1,2,3,4]
b=[]
for i in a:
    b.append(i*2)
print(b)


[2, 4, 6, 8]


In [ ]:
a=[1,2,3,4,5,6,7,8,9]
b=[i-1 for i in a]
print(b)

[0, 1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
# To install a library, use the following command:
# !pip install <library_name>

# For example, to install the pandas library:
!pip install pandas

NumPy numeric pyhthon


In [ ]:
import numpy as np


In [ ]:
# creating Array and matrix
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6]])

print(a)
print(b)

In [ ]:
#Arithmetic
x = np.array([10, 20, 30])
y = np.array([1, 2, 3])

print(x + y)
print(x - y)
print(x * y)
print(x / y)

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


In [ ]:
# Ststistic
data = np.array([10, 20, 30, 40, 50])

print(np.mean(data))
print(np.median(data))
print(np.std(data))
print(np.sum(data))
print(np.max(data))
print(np.min(data))

30.0
30.0
14.142135623730951
150
50
10


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.reshape(3, 2))  # Reshape into 3 rows, 2 cols
print(arr.flatten())   #Matrix array in flat

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [ ]:
a = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print(np.dot(a, B))  # Matrix multiplication
print(B.T)   #The column will transpose a row

[[19 22]
 [43 50]]
[[5 7]
 [6 8]]


In [ ]:
arr = np.array([[10, 20, 30],
                [40, 50, 60]])

print(arr[1,2])     # Single element → 20
print(arr[1])        # Entire 2nd row → [40 50 60]
print(arr[:,1])     # Entire 2nd column → [20 50]
print(arr[1, 0:2])  # 2nd row, 1st and 2nd columns → [40 50]

60
[40 50 60]
[20 50]
[40 50]


In [ ]:
print(np.zeros((2,3)))  # 2x3 matrix of zeros
print(np.ones((2,2)))   # 2x2 matrix of ones
print(np.eye(3))        # 3x3 Identity matrix

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Comparision Operator in Array

In [ ]:
arr = np.array([10, 20, 30, 40])
print(arr > 25)      # [False False  True  True]
print(arr[arr > 25]) # Filter values → [30 40]

[False False  True  True]
[30 40]


Creating Random Matrix


In [ ]:
print(np.random.rand(2,3))   # Random values between 0–1
print(np.random.randint(1,10,5)) # 5 random integers from 1–9
print(np.random.choice(['a','e','i','o','u'],(3,3)))
print(np.random.choice([1,2,3,4,5],(3,3)))
 #

[[0.83843074 0.24196943 0.67699163]
 [0.22370338 0.21003041 0.40392735]]
[4 4 9 3 9]
[['a' 'e' 'o']
 ['a' 'u' 'a']
 ['o' 'e' 'u']]
[[2 5 5]
 [2 4 2]
 [5 4 2]]


In [ ]:
arr = np.array([1.2, 2.5, 3.8])
print(np.round(arr))  # → [1. 2. 4.]
print(arr.astype(int))# Convert to integer

[1. 2. 4.]
[1 2 3]
